name: Rust

on:
  push:
    branches: [ "master", "developer" ]
  pull_request:
    branches: [ "master", "developer" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --all
    - name: Run tests
      run: cargo test --all
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: fmtCheck
      run: cargo fmt --check
